version: "3"

services:
  backend:
    build:
      context: ./backend
    command: npm start
    environment:
      - NODE_ENV=docker_compose
      - PORT=8080
    ports: 
      - 8080:8080
    volumes:
      - ./backend:/usr/src/app      
    depends_on: 
      - postgres
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000      

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=knex
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=knex
    ports:
      - 5432:5432
    
      