# pull the official base image
FROM node:alpine
# set working direction
WORKDIR /usr/src/app
# add `/app/node_modules/.bin` to $PATH
ENV PATH usr/src/app/node_modules/.bin:$PATH
# install application dependencies
COPY . .
COPY package.json ./
COPY package-lock.json ./
RUN npm install
RUN npm run build
# add app

# start app lauching a server that serves the frontend
CMD ["npm", "run", "start"]